spring:
  application:
    name: RateLimitServerRedisJedis
  data:
    redis:
      port: 6379
      host: localhost
logging:
  level:
    com.giffing.bucket4j: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

bucket4j:
  cache-to-use: redis-jedis
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  enabled: true
  filters:
    - cache-name: buckets_test
      id: filter1
      filter-method: servlet
      url: .*
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
              refill-speed: interval
server:
  port: 8083
